version: "3.7"

volumes:
  caddy_data:

services:
  caddy:
    image: "caddy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      # static files like the entrypoint index.html with links to the RPd notebook collections
      - ./static/:/usr/share/caddy/
      - ./Caddyfile:/etc/caddy/Caddyfile
  covid:
    image: "jupyter/minimal-notebook"
    command: "start-notebook.sh --NotebookApp.base_url=/covid"
    volumes:
      # 1 hour lost on fucking "jovYan" NOT "joyVan" omg...
      - "./covid/:/home/jovyan/work"
    environment:
      - "JUPYTER_TOKEN=test"
  other:
    image: "jupyter/minimal-notebook"
    command: "start-notebook.sh --NotebookApp.base_url=/other"
    volumes:
      # each collection of notebooks is mounted to its respective jupyter notebook server container
      - "./other/:/home/jovyan/work"
    environment:
      # they can each have their own tokens
      # these should DEFINITELY not be hard-coded in the docker-compose
      - "JUPYTER_TOKEN=test"
